#!/bin/bash
ARGUMENT=$1;
if [[ -f $ARGUMENT ]]; then
    sed -E -i.original 's/\x0D"/"/g' $ARGUMENT
else
	echo "remove_embedded_cr (c) 2024 Ed Trager"
	echo "remove_embedded_cr removes U+000D (ASCII CARRIAGE RETURN)"
	echo "when present at the END of a quoted string, e.g.:"
	echo ''
	echo '   "blah blah blah0x0D"'
	echo ''
	echo 'Corrected output will be:'
	echo ''
	echo '   "blah blah blah"'
	echo ''
	echo 'USAGE:'
	echo ''
	echo 'remove_embedded_cr <some_data_file>'
	echo ''
	echo 'Original file will be preserved with an extension of ".original"'
	echo ''
    exit 1
fi

