#!/bin/bash
ARGUMENT=$1;
if [[ -f $ARGUMENT ]]; then
    # GET HERE IF FILE ARGUMENT IS VALID:
    # USE sed MAGIC TO DO THE WORK:
    #
    # STEP 1: Get rid of existing double-quote delimiters, if present:
    #         1.1: Remove any double quote at beginning of the very first column
    #         1.2: Remove any double quote at the very end of the last column
    #         1.3: Remove any double quotes that are "sandwiching" the tabs
    #               -- that is to say, remaining double quotes that are either
    #                  terminating or beginning quoted strings of all the columns
    #                  excluding what was already removed from the first and last column
    #
    # STEP 2: Substitute any embedded ASCII commas        with UNICODE U+201A `‚`
    # STEP 3: Substitute any embedded ASCII double quotes with UNICODE U+201D `”`
    # STEP 4: Substitute the now completely "bare" tabs with ASCII commas
    #
    # The substituted Unicode characters, should they appear, maintain the same semantic
    # values but do not interfere with file parsing in the way that the original ASCII
    # characters may have.
    #
    sed -E -i.original 's/^"//;s/"$//;s/"\t"/\t/g;s/"\t/\t/g;s/\t"/\t/g;s/,/‚/g;s/"/”/g;s/\t/,/g' $ARGUMENT
else
    echo "tsv2csv is (c) 2022 by Edward H. Trager."
    echo "Usage is: tsv2csv <tab_delimited_file>"
    echo "File will be converted to a comma-delimited file."
    echo "Original unchanged files will have «.original» added to the file name."
    echo "For a complete explanation of how this works, please read the comments"
    echo "that precede the code in the script."
    exit 1
fi

